#!/bin/sh

set -x

mkdir -p dev proc sys run
mount -t devtmpfs dev dev
mkdir -p dev/pts dev/shm
mount -t devpts devpts dev/pts
mount -t tmpfs tmpfs dev/shm
mount -t proc proc proc
mount -t sysfs sysfs sys
mount -t tmpfs tmpfs run
mkdir -p run/lock run/shm
