#!/bin/bash

TARGET=${1-PWD}
shift

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT
chmod u+x "$TMP"

set -e

cat >"$TMP" <<END
#!/bin/bash

set -e -x

: Entered mount namespace

mount -t devtmpfs dev "$TARGET/dev"
mkdir -p "$TARGET/dev/pts"
mount -t devpts devpts "$TARGET/dev/pts"
mount -t proc proc "$TARGET/proc"
mount -t sysfs sysfs "$TARGET/sys"
mount -t tmpfs tmpfs "$TARGET/run"
mkdir -p "$TARGET/run/lock" "$TARGET/run/shm"

END
if [ "$#" = 0 ]; then
    echo chroot "$TARGET" >>"$TMP"
else
    echo chroot "$TARGET" "$@" >>"$TMP"
fi

unshare -m -- "$TMP"
